### ISSUE TITLE
errors on bee run -gendoc=true

### ISSUE THREAD

**Issue by ahdai0718** [beego/bee#285]
```
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.5.1

├── Beego     : 1.7.0
├── GoVersion : go1.6.3
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : /Users/Ahdai/Dropbox/Cases/Go
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Friday, 23 Sep 2016
```

```
2016/09/23 14:23:44 [INFO] Start building...
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.5.1
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x592180, 0xc8200100a0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
main.parseObject(0xc821b21900, 0xc821b1b6d4, 0xc, 0xc8202d66e0, 0xc8202d6758, 0xc821a41e00)
	/Users/Ahdai/Dropbox/Cases/Go/src/github.com/beego/bee/g_docs.go:668 +0x1173
main.getModel(0xc820330a69, 0x13, 0xc820330a69, 0x6, 0xc820330a70, 0xc, 0x0, 0x0, 0xc821b1b6d4, 0xc, ...)
	/Users/Ahdai/Dropbox/Cases/Go/src/github.com/beego/bee/g_docs.go:615 +0x638
main.parserComments(0xc8203336a0, 0xc820334530, 0x8, 0xc821a4c420, 0x15, 0xc82013d661, 0x16, 0x0, 0x0)
	/Users/Ahdai/Dropbox/Cases/Go/src/github.com/beego/bee/g_docs.go:395 +0x1ad7
main.analisyscontrollerPkg(0x0, 0x0, 0xc82013d661, 0x16)
	/Users/Ahdai/Dropbox/Cases/Go/src/github.com/beego/bee/g_docs.go:290 +0xa43
main.generateDocs(0xc82000a034, 0x2c)
	/Users/Ahdai/Dropbox/Cases/Go/src/github.com/beego/bee/g_docs.go:100 +0x571
main.generateCode(0x92d5e0, 0xc82000a1d0, 0x1, 0x1, 0x0)
	/Users/Ahdai/Dropbox/Cases/Go/src/github.com/beego/bee/g.go:129 +0x405
main.main()
	/Users/Ahdai/Dropbox/Cases/Go/src/github.com/beego/bee/bee.go:115 +0x376
2016/09/23 14:23:44 ============== generate docs ===================
```

I found the problem caused by models have a property with type `map[string]map[string]string`.
Maybe the type just not be supported in this version.

I fix the problem temporarily, and it works for me now.

g_docs.go:667
```
					if len(typeFormat) > 1 {
						mp.Format = typeFormat[1]
					}
```

**Comment by astaxie** [comment]
@ahdai0718 please update to bee 1.5.2. it fix now 😄

**Comment by ahdai0718** [comment]
@astaxie okp, cool.
