### ISSUE TITLE
Running tests creates routers/commentRouter with odd name

### ISSUE THREAD

**Issue by mdhender** [beego/bee#485]
When I run `goconvey` in a new api project, a new router/commentsRouter_controller file is created that has the path to the file embedded in the name: `commentsRouter__________________________________Volumes_ssda_mdhender_Software_go_src_github_com_mdhender_tc_controllers.go`. The file contents are identical to the router/commentsRouter_controller.go created by `bee run`.

I am using the latest bee and beego from github. I ran an update this morning:
`
$ go get -u github.com/astaxie/beego
$ go get -u github.com/beego/bee
`

I am running on a Mac, macOS High Sierra (10.13), with Go version 1.9.1. I get the odd file name by the following steps:

`
$ bee api tc
$ cd tc
$ bee run
$ goconvey
$ ls -l routers/commentsRouter_*.go
-rw-r--r--  1 mdhender  staff  4101 Nov  5 09:39 routers/commentsRouter__________________________________Volumes_ssda_mdhender_Software_go_src_github_com_mdhender_tc_controllers.go
-rw-r--r--  1 mdhender  staff  4101 Nov  5 09:38 routers/commentsRouter_controllers.go
`

Here's the full log:

```
macpro:mdhender mdhender$ bee version
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.9.1

├── Beego     : 1.9.0
├── GoVersion : go1.9.1
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 12
├── GOPATH    : /Volumes/ssda/mdhender/Software/go
├── GOROOT    : /usr/local/Cellar/go/1.9.1/libexec
├── Compiler  : gc
└── Date      : Sunday, 5 Nov 2017

macpro:mdhender mdhender$ bee api tc
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.9.1
2017/11/05 09:37:48 INFO     ▶ 0001 Creating API...
	create	 /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc
	create	 /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/conf
	create	 /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/controllers
	create	 /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/tests
	create	 /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/conf/app.conf
	create	 /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/models
	create	 /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/routers/
	create	 /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/controllers/object.go
	create	 /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/controllers/user.go
	create	 /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/tests/default_test.go
	create	 /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/routers/router.go
	create	 /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/models/object.go
	create	 /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/models/user.go
	create	 /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/main.go
2017/11/05 09:37:48 SUCCESS  ▶ 0002 New API successfully created!

macpro:mdhender mdhender$ cd tc && ls -l routers
/Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc
total 8
-rw-r--r--  1 mdhender  staff  650 Nov  5 09:37 router.go

macpro:tc mdhender$ bee run
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.9.1
2017/11/05 09:38:46 INFO     ▶ 0001 Using 'tc' as 'appname'
2017/11/05 09:38:46 INFO     ▶ 0002 Initializing watcher...
github.com/mdhender/tc/models
github.com/mdhender/tc/controllers
github.com/mdhender/tc/routers
github.com/mdhender/tc
2017/11/05 09:38:48 SUCCESS  ▶ 0003 Built Successfully!
2017/11/05 09:38:48 INFO     ▶ 0004 Restarting 'tc'...
2017/11/05 09:38:48 SUCCESS  ▶ 0005 './tc' is running...
2017/11/05 09:38:48 [I] [parser.go:96] generate router from comments
2017/11/05 09:38:48 [I] [router.go:244] /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/controllers no changed
2017/11/05 09:38:48 [I] [asm_amd64.s:2337] http server Running on http://:8080
github.com/mdhender/tc/routers
github.com/mdhender/tc
2017/11/05 09:38:50 SUCCESS  ▶ 0006 Built Successfully!
2017/11/05 09:38:50 INFO     ▶ 0007 Restarting 'tc'...
2017/11/05 09:38:50 SUCCESS  ▶ 0008 './tc' is running...
2017/11/05 09:38:50 [I] [router.go:244] /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/controllers no changed
2017/11/05 09:38:50 [I] [router.go:244] /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/controllers no changed
2017/11/05 09:38:50 [I] [asm_amd64.s:2337] http server Running on http://:8080
^C

macpro:tc mdhender$ ls -l routers
total 24
-rw-r--r--  1 mdhender  staff  4101 Nov  5 09:38 commentsRouter_controllers.go
-rw-r--r--  1 mdhender  staff   650 Nov  5 09:37 router.go

macpro:tc mdhender$ goconvey
2017/11/05 09:39:16 goconvey.go:61: Initial configuration: [host: 127.0.0.1] [port: 8080] [poll: 250ms] [cover: true]
2017/11/05 09:39:16 tester.go:19: Now configured to test 10 packages concurrently.
2017/11/05 09:39:16 goconvey.go:192: Serving HTTP at: http://127.0.0.1:8080
2017/11/05 09:39:16 goconvey.go:105: Launching browser on 127.0.0.1:8080
2017/11/05 09:39:16 integration.go:122: File system state modified, publishing current folders... 0 12079212758
2017/11/05 09:39:16 goconvey.go:118: Received request from watcher to execute tests...
2017/11/05 09:39:16 executor.go:69: Executor status: 'executing'
2017/11/05 09:39:16 coordinator.go:46: Executing concurrent tests: github.com/mdhender/tc/controllers
2017/11/05 09:39:16 coordinator.go:46: Executing concurrent tests: github.com/mdhender/tc/models
2017/11/05 09:39:16 coordinator.go:46: Executing concurrent tests: github.com/mdhender/tc/tests
2017/11/05 09:39:16 coordinator.go:46: Executing concurrent tests: github.com/mdhender/tc/conf
2017/11/05 09:39:16 coordinator.go:46: Executing concurrent tests: github.com/mdhender/tc
2017/11/05 09:39:16 coordinator.go:46: Executing concurrent tests: github.com/mdhender/tc/routers
2017/11/05 09:39:16 goconvey.go:113: 
2017/11/05 09:39:16 shell.go:102: Coverage output: ?   	github.com/mdhender/tc/models	[no test files]
2017/11/05 09:39:16 shell.go:104: Run without coverage
2017/11/05 09:39:17 shell.go:102: Coverage output: ?   	github.com/mdhender/tc	[no test files]
2017/11/05 09:39:17 shell.go:104: Run without coverage
2017/11/05 09:39:17 shell.go:102: Coverage output: ?   	github.com/mdhender/tc/routers	[no test files]
2017/11/05 09:39:17 shell.go:104: Run without coverage
2017/11/05 09:39:17 shell.go:102: Coverage output: ?   	github.com/mdhender/tc/controllers	[no test files]
2017/11/05 09:39:17 shell.go:104: Run without coverage
2017/11/05 09:39:17 shell.go:102: Coverage output: 2017/11/05 09:39:17 [I] generate router from comments
2017/11/05 09:39:17 [I] /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/controllers no changed
panic: the target config file: /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/tests/conf/app.conf don't exist

goroutine 1 [running]:
github.com/astaxie/beego.InitBeegoBeforeTest(0xc420084a80, 0x51)
	/Volumes/ssda/mdhender/Software/go/src/github.com/astaxie/beego/beego.go:98 +0xc2
github.com/astaxie/beego.TestBeegoInit(0xc42001aa50, 0x43)
	/Volumes/ssda/mdhender/Software/go/src/github.com/astaxie/beego/beego.go:92 +0xbe
github.com/mdhender/tc/tests.init.0()
	/Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/tests/default_test.go:18 +0xc9
github.com/mdhender/tc/tests.init()
	<autogenerated>:1 +0x6c
main.init()
	<autogenerated>:1 +0x5a
exit status 2
FAIL	github.com/mdhender/tc/tests	0.021s
2017/11/05 09:39:17 shell.go:104: Run without coverage
2017/11/05 09:39:17 integration.go:122: File system state modified, publishing current folders... 12079212758 13589116816
2017/11/05 09:39:18 parser.go:24: [no test files]: github.com/mdhender/tc/controllers
2017/11/05 09:39:18 parser.go:24: [no test files]: github.com/mdhender/tc/models
2017/11/05 09:39:18 parser.go:24: [no test files]: github.com/mdhender/tc/routers
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: 2017/11/05 09:39:18 [I] /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/controllers no changed
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: 2017/11/05 09:39:18 [I] /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/controllers no changed
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: panic: the target config file: /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/tests/conf/app.conf don't exist
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: 
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: goroutine 1 [running]:
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: github.com/astaxie/beego.InitBeegoBeforeTest(0xc420082720, 0x51)
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: /Volumes/ssda/mdhender/Software/go/src/github.com/astaxie/beego/beego.go:98 +0xc2
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: github.com/astaxie/beego.TestBeegoInit(0xc42001a7d0, 0x43)
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: /Volumes/ssda/mdhender/Software/go/src/github.com/astaxie/beego/beego.go:92 +0xbe
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: github.com/mdhender/tc/tests.init.0()
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/tests/default_test.go:18 +0xc9
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: github.com/mdhender/tc/tests.init()
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: <autogenerated>:1 +0x6c
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: main.init()
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: <autogenerated>:1 +0x53
2017/11/05 09:39:18 parser.go:24: [failed]: github.com/mdhender/tc/tests
2017/11/05 09:39:18 parser.go:24: [no test files]: github.com/mdhender/tc
2017/11/05 09:39:18 parser.go:24: [no go code]: github.com/mdhender/tc/conf
2017/11/05 09:39:18 executor.go:69: Executor status: 'idle'
2017/11/05 09:39:18 goconvey.go:118: Received request from watcher to execute tests...
2017/11/05 09:39:18 executor.go:69: Executor status: 'executing'
2017/11/05 09:39:18 coordinator.go:46: Executing concurrent tests: github.com/mdhender/tc/controllers
2017/11/05 09:39:18 coordinator.go:46: Executing concurrent tests: github.com/mdhender/tc/tests
2017/11/05 09:39:18 coordinator.go:46: Executing concurrent tests: github.com/mdhender/tc/routers
2017/11/05 09:39:18 coordinator.go:46: Executing concurrent tests: github.com/mdhender/tc
2017/11/05 09:39:18 coordinator.go:46: Executing concurrent tests: github.com/mdhender/tc/models
2017/11/05 09:39:18 coordinator.go:46: Executing concurrent tests: github.com/mdhender/tc/conf
2017/11/05 09:39:19 shell.go:102: Coverage output: ?   	github.com/mdhender/tc/models	[no test files]
2017/11/05 09:39:19 shell.go:104: Run without coverage
2017/11/05 09:39:19 shell.go:102: Coverage output: ?   	github.com/mdhender/tc/controllers	[no test files]
2017/11/05 09:39:19 shell.go:104: Run without coverage
2017/11/05 09:39:19 shell.go:102: Coverage output: ?   	github.com/mdhender/tc/routers	[no test files]
2017/11/05 09:39:19 shell.go:104: Run without coverage
2017/11/05 09:39:19 shell.go:102: Coverage output: 2017/11/05 09:39:19 [I] /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/controllers no changed
2017/11/05 09:39:19 [I] /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/controllers no changed
panic: the target config file: /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/tests/conf/app.conf don't exist

goroutine 1 [running]:
github.com/astaxie/beego.InitBeegoBeforeTest(0xc420084720, 0x51)
	/Volumes/ssda/mdhender/Software/go/src/github.com/astaxie/beego/beego.go:98 +0xc2
github.com/astaxie/beego.TestBeegoInit(0xc42001a7d0, 0x43)
	/Volumes/ssda/mdhender/Software/go/src/github.com/astaxie/beego/beego.go:92 +0xbe
github.com/mdhender/tc/tests.init.0()
	/Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/tests/default_test.go:18 +0xc9
github.com/mdhender/tc/tests.init()
	<autogenerated>:1 +0x6c
main.init()
	<autogenerated>:1 +0x5a
exit status 2
FAIL	github.com/mdhender/tc/tests	0.019s
2017/11/05 09:39:19 shell.go:104: Run without coverage
2017/11/05 09:39:19 shell.go:102: Coverage output: ?   	github.com/mdhender/tc	[no test files]
2017/11/05 09:39:19 shell.go:104: Run without coverage
2017/11/05 09:39:20 parser.go:24: [no test files]: github.com/mdhender/tc/controllers
2017/11/05 09:39:20 parser.go:24: [no test files]: github.com/mdhender/tc/models
2017/11/05 09:39:20 parser.go:24: [no test files]: github.com/mdhender/tc/routers
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: 2017/11/05 09:39:20 [I] /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/controllers no changed
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: 2017/11/05 09:39:20 [I] /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/controllers no changed
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: panic: the target config file: /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/tests/conf/app.conf don't exist
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: 
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: goroutine 1 [running]:
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: github.com/astaxie/beego.InitBeegoBeforeTest(0xc420082720, 0x51)
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: /Volumes/ssda/mdhender/Software/go/src/github.com/astaxie/beego/beego.go:98 +0xc2
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: github.com/astaxie/beego.TestBeegoInit(0xc42001a7d0, 0x43)
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: /Volumes/ssda/mdhender/Software/go/src/github.com/astaxie/beego/beego.go:92 +0xbe
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: github.com/mdhender/tc/tests.init.0()
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: /Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/tests/default_test.go:18 +0xc9
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: github.com/mdhender/tc/tests.init()
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: <autogenerated>:1 +0x6c
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: main.init()
Potential error parsing output of github.com/mdhender/tc/tests ; couldn't handle this stray line: <autogenerated>:1 +0x53
2017/11/05 09:39:20 parser.go:24: [failed]: github.com/mdhender/tc/tests
2017/11/05 09:39:20 parser.go:24: [no test files]: github.com/mdhender/tc
2017/11/05 09:39:20 parser.go:24: [no go code]: github.com/mdhender/tc/conf
2017/11/05 09:39:20 executor.go:69: Executor status: 'idle'
^C

macpro:tc mdhender$ ls -l routers
total 40
-rw-r--r--  1 mdhender  staff  4101 Nov  5 09:39 commentsRouter__________________________________Volumes_ssda_mdhender_Software_go_src_github_com_mdhender_tc_controllers.go
-rw-r--r--  1 mdhender  staff  4101 Nov  5 09:38 commentsRouter_controllers.go
-rw-r--r--  1 mdhender  staff   650 Nov  5 09:37 router.go

macpro:tc mdhender$ diff routers/commentsRouter_*.go

macpro:tc mdhender$ cksum routers/commentsRouter_*.go
1270915166 4101 routers/commentsRouter__________________________________Volumes_ssda_mdhender_Software_go_src_github_com_mdhender_tc_controllers.go
1270915166 4101 routers/commentsRouter_controllers.go
```

**Comment by mdhender** [comment]
I'm not sure if this issue should be opened in astaxie/beego. The problem seems to be astaxie/beego/parser.go. When running `bee run`, the working directory is my project (tc, in this case). The `commentFilename` variable is set to `commentsRouter_controllers.go`. The `no changed` log message shows the absolute file path.

When running tests, the working directory is `tc/tests`. The `no changed` log message still shows the absolute file path, but inspecting the results of the line
`commentFilename, _ := filepath.Rel(AppPath, pkgRealPath)`
shows that the path is extremely relative: `../../../../../../../../../../../Volumes/ssda/mdhender/Software/go/src/github.com/mdhender/tc/controllers`. In the next statement, all those `../` sequences get replaced with underscores, which results in the odd filename.
