### ISSUE TITLE
MySQL 8.0 使用bee generate appcode生成源码失败

### ISSUE THREAD

**Issue by KusTa** [beego/bee#607]
同一套库表结构, 执行相同的Bee cli:
    `bee generate appcode -tables="table_test" -driver=mysql -conn="root:123456@tcp(localhost:32783)/test" -level=3`

在使用 MySQL 8.0.16 时报错:

    >  FATAL    ▶ 0006 Could not query INFORMATION_SCHEMA for PK/UK/FK information

而MySQL 5.5.62 则正常.

Bee是不支持高版本MySQL吗 ? 

p.S : 假如抛弃bee脚手架, 直接使用Beego开发, 其ORM等类似组件会有这类问题吗 ?

谢谢

**Comment by guhan121** [comment]
@KusTa 直接撸代码就可以了。

**Comment by sunxing-1** [comment]
Could not query INFORMATION_SCHEMA for PK/UK/FK information

**Comment by sunxing-1** [comment]
2020/07/12 22:52:34 INFO     ▶ 0001 Using 'mysql' as 'SQLDriver'
2020/07/12 22:52:34 INFO     ▶ 0002 Using 'root:123456@tcp(127.0.0.1:3306)/beegodb' as 'SQLConn'
2020/07/12 22:52:34 INFO     ▶ 0003 Using 'news' as 'Tables'
2020/07/12 22:52:34 INFO     ▶ 0004 Using '3' as 'Level'
2020/07/12 22:52:34 INFO     ▶ 0005 Analyzing database tables...
panic: runtime error: index out of range [2] with length 0

goroutine 1 [running]:
github.com/beego/bee/generate.extractIntSignness(0xc00020b0a3, 0x3, 0xc00020b09c, 0x3)
        D:/workspace/src/github.com/beego/bee/generate/g_appcode.go:928 +0xc6
github.com/beego/bee/generate.(*MysqlDB).GetColumns(0x1307b98, 0xc00024e000, 0xc0002003c0, 0xc0002027e0)
        D:/workspace/src/github.com/beego/bee/generate/g_appcode.go:479 +0xf9b
github.com/beego/bee/generate.getTableObjects(0xc000204500, 0x1, 0x1, 0xc00024e000, 0xdd0ae0, 0x1307b98, 0x0, 0x1, 0xc00009dad8)
        D:/workspace/src/github.com/beego/bee/generate/g_appcode.go:361 +0x1de
github.com/beego/bee/generate.gen(0xc00020acf2, 0x5, 0xc0002485d0, 0x27, 0xc00009dc07, 0xc00009dc40, 0xc0002121c0, 0x10)
        D:/workspace/src/github.com/beego/bee/generate/g_appcode.go:314 +0x2db
github.com/beego/bee/generate.GenerateAppcode(0xc00020acf2, 0x5, 0xc0002485d0, 0x27, 0x1278793, 0x1, 0xc00020acf8, 0x4, 0xc0002121c0, 0x10)
        D:/workspace/src/github.com/beego/bee/generate/g_appcode.go:293 +0x212
github.com/beego/bee/cmd/commands/generate.appCode(0x12ba8c0, 0xc00009e020, 0x3, 0x6, 0xc0002121c0, 0x10)
        D:/workspace/src/github.com/beego/bee/cmd/commands/generate/generate.go:167 +0x676
github.com/beego/bee/cmd/commands/generate.GenerateCode(0x12ba8c0, 0xc00009e020, 0x3, 0x6, 0x6)
        D:/workspace/src/github.com/beego/bee/cmd/commands/generate/generate.go:100 +0x3f4
main.main()
        D:/workspace/src/github.com/beego/bee/main.go:75 +0x2dc

**Comment by sunxing-1** [comment]
这个报错是什么问题呢

**Comment by sunxing-1** [comment]
mysql 8.0.20
go version go1.14.4 windows/amd64
beego 1.12

**Comment by ZhangX-Byte** [comment]
问题解决了吗？

**Comment by ehomecd** [comment]
遇到同样问题

**Comment by supermanfeng** [comment]
兄弟问题解决了吗

**Comment by flycash** [comment]
等我=。=忙了一两个月都快忘了=。=

**Comment by flycash** [comment]
求提供一下表结构定义，我这里试了一下，没复现出来，所以不清楚是不是我的表结构太简单还是啥的。
