### ISSUE TITLE
Failed to new application

### ISSUE THREAD

**Issue by gotostack** [beego/bee#706]
$ bee new hello
2020/07/31 13:56:09 INFO     ▶ 0001 generate new project support go modules.
2020/07/31 13:56:09 INFO     ▶ 0002 Creating application...
	create	 /home/yulong/go/src/hello/go.mod
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/beego/bee/utils.GetGoVersionSkipMinor(0xc000295ac8, 0x2)
	/home/yulong/go/pkg/mod/github.com/beego/bee@v1.12.0/utils/utils.go:453 +0xed
github.com/beego/bee/cmd/commands/new.CreateApp(0x1381480, 0xc0000321a0, 0x1, 0x1, 0x0)
	/home/yulong/go/pkg/mod/github.com/beego/bee@v1.12.0/cmd/commands/new/new.go:312 +0x545
main.main()
	/home/yulong/go/pkg/mod/github.com/beego/bee@v1.12.0/main.go:75 +0x2df

**Comment by gotostack** [comment]
v1.11.1 works fine!
