### ISSUE TITLE
运行bee api参数不足时的错误信息需要改进，而不是panic。

### ISSUE THREAD

**Issue by alex-lx** [beego/bee#98]
```
> go api
panic: runtime error: index out of range

goroutine 1 [running]:
main.createapi(0x9e5e00, 0x124e2128, 0x0, 0x0, 0x0)
        E:/go_workspace/src/github.com/beego/bee/apiapp.go:553 +0x2df0
main.main()
        E:/go_workspace/src/github.com/beego/bee/bee.go:113 +0x2e1
```

**Comment by astaxie** [comment]
你执行的是什么命令？
